### ISSUE TITLE
Add building, cleaning, and printing to runner

### ISSUE THREAD

**Issue by mhuzai** [ILLIXR/ILLIXR#126]
There is no way to just build plugins or clean them at the moment. Having such functionality would ease development. It would also be nice to have the runner print out the command to run ILLIXR or Monado, so we can plug in the command in profiling tools.

Desired commands:

- [ ] Build plugins
- [x] "Make clean" plugin directories
- [ ] Print full run command (`runtime.exe A/plugin.opt.so B/...`)

**Comment by charmoniumQ** [comment]
To make that feasible, I suggest using the existing usage paradigm: actions and action options.

- `clean` should be a new action that calls `make clean`
- `print` should be a new action that does not compile anything,
- `build` should reuse `native` and set the `command` to `echo $env_cmd`.

To avoid ad-hockery, we can say `./runner.sh config.yaml [key1.key2.key3=val ...]` runs `config.yaml` while overriding some of its options (`config["key1"]["key2"]["key3"] = val`).

To make this user-friendly, we should make a table of aliases which expand to a bunch of overrides. The actual invocation is: `./runner.sh config.yaml config.yaml [alias ...] [key1.key2.key3 = val ...]`, where the alias `build` maps to the overrides `action=native action.command='echo $env_cmd'`.

**Comment by astro-friedel** [comment]
The new build CMake build system automatically provides two of the requested features. I will add code to print out the command line.
