### ISSUE TITLE
Make the default resolution 2K

### ISSUE THREAD

**Issue by mhuzai** [ILLIXR/ILLIXR#132]
Right now the default is a small VGA-sized window which has to be manually updated to 2K for any profiling experiments. Furthermore, the runtime (extended_window), timewarp, and hologram each independently define their own window size. The window size needs to be unified (initially in a header file, eventually in YAML) and needs to be set to 2K by default.

**Comment by DhairyaBahl** [comment]
If this issue is still there then kindly assign me to it.

**Comment by charmoniumQ** [comment]
Thanks for showing interest @DhairyaBahl :smile: . Please read our [contributing guidelines](https://github.com/ILLIXR/ILLIXR/blob/cb1888a54c4cf31647a3ee4b531a38945ff21d39/CONTRIBUTING.md) (you're at step 3).

**Comment by Zee2** [comment]
This is yet another thing that should be put in a config somewhere and distributed through Switchboard/Phonebook... Quite a few different moving parts all need to agree on various image/texture dimensions. This also includes things like the camera dimensions; `debugview` displays camera frames coming from the camera component; it would be great if the cameras, eyebuffers, etc etc can all be configured through YAML/JSON and shared/published between all the components. @charmoniumQ this is another instance of dense/complex shared config like I was talking about

**Comment by DhairyaBahl** [comment]
@mhuzai I would like to work on this issue but i was not in touch with this issue from a long time, so i have to start from beginning if you don't mind. 

Thanks :)

**Comment by mhuzai** [comment]
That's alright but we do need this soon.

**Comment by DhairyaBahl** [comment]
@mhuzai I am on it. Will do my best to complete this asap.

Thanks :)

**Comment by DhairyaBahl** [comment]
@mhuzai Kindly tell me if just changing the parameters of 

        xlib_gl_extended_window(int _width, int _height, GLXContext _shared_gl_context){
            width = _width;
            height = _height;

int the extended_window.hpp and also doing the same with parameters in gldemo timewarp and plugin.cpp files will solve this issue. 

Kindly guide Thanks :)

**Comment by mhuzai** [comment]
No, it will not. Please look at our [previous conversation](https://github.com/ILLIXR/ILLIXR/pull/139#discussion_r494742101). Ask if something is unclear.

**Comment by DhairyaBahl** [comment]
@mhuzai Okay . No issues :)
