### ISSUE TITLE
Consider using "non-null" pointer type

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#160]
In _most_ cases, our pointers should never be null. By converting `std::{shared,unique}_ptr` types to `nn_{shared,unique}_ptr`
([nn library][1]), the C++ type checker can statically verify that pointers are non-null.

Perhaps run-of-the-mill C++ references could also satisfy that need.

[1]: https://github.com/dropbox/nn

**Comment by astro-friedel** [comment]
The nn library was archived 5 years ago and has had no updates in 7 years.
