### ISSUE TITLE
install_dep.sh script should add libsqlite3-dev package

### ISSUE THREAD

**Issue by YQGong** [ILLIXR/ILLIXR#161]
if libsqlite3-dev package was not installed, a strange error will occur when running `./runner.sh config/native.yaml` and the error message won't lead to install libsqlite3-dev but missing some OpenGL libs.

**Comment by mhuzai** [comment]
It already installs [libsqlite3-dev](https://github.com/ILLIXR/ILLIXR/blob/master/scripts/install_apt_deps.sh#L11).
Can you share your error message?

**Comment by YQGong** [comment]
Sorry, after I installed libsqlite3-dev the program ran perfectly, and the error messages are lost. I just follow the instruction here: https://illixr.github.io/ILLIXR/getting_started/

Maybe the commit about sqlite3-dev is not included in the branch used in the above page. (v1-latest and v2-latest)

By the way, I think this manual is out of date. Could you provide the latest version of the manual?

**Comment by mhuzai** [comment]
Thanks for pointing out the out-of-date documentation. We'll fix in the upcoming release.
