### ISSUE TITLE
Cannot build librealsense2-dkms for Ubuntu 20 LTS

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#176]
The IntelRealSense project does not yet support the LTS kernels for Ubuntu 20.04 (See installation process [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md)).

From a fresh, up-to-date copy of Ubuntu 20.04, following the [ILLIXR getting started page](https://illixr.github.io/ILLIXR/getting_started) while using the 'master' branch produces the following error:
`Building initial module for 5.4.0-52-generic
Error!  The /var/lib/dkms/librealsense2-dkms/1.3.14/5.4.0-52-generic/x86_64/dkms.conf for module librealsense2-dkms includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.`

It appears that this issue has been encountered before, and that some success can be found by building the SDK manually using the project's "backend" installation process. See [Issue #6436](https://github.com/IntelRealSense/librealsense/issues/6436) at the IntelRealSense repository.

**Comment by mhuzai** [comment]
Hi stranger. Thanks for the detailed info. It seems the easiest way forward is to install librealsense automatically only if the OS is 18.04. For non-18.04 OSes, we can have the users install it themselves.

If you can change scripts/install_apt_deps.sh accordingly and open a PR, that would be great.
