### ISSUE TITLE
Fix plugin documentation

### ISSUE THREAD

**Issue by mhuzai** [ILLIXR/ILLIXR#181]
Step 2 of the writing your plugin tutorial should be `common/common.mk`

**Comment by charmoniumQ** [comment]
Step 6: Define `virtual void _p_one_iteration() override {}`

Q: "Where should I put my plugin's code?" A: "If periodically scheduled, `_p_one_iteration`. If data-driven, `sb->schedule(...)`.

`threadloop` inherits from `plugin`, but adds threading functionality, so if you don't use `_p_one_iteration`, inheriting from `threadloop` is superfluous; Inherit from `plugin` directly instead.

**Comment by charmoniumQ** [comment]
- Update the `v2-latest` pointer

- Explain when one should clone from `master`

- Use `--single-branch --branch ${branch_name` for speed (or maybe delete old branches).

**Comment by astro-friedel** [comment]
The new documentation has been rewritten for the cmake build system
