### ISSUE TITLE
Update the plugins page to have a list of topics

### ISSUE THREAD

**Issue by therishidesai** [ILLIXR/ILLIXR#186]
Right now the only way to know what topics a plugin is publishing and subscribing to is via the code. We need to update the docs to make this easier to figure out.

**Comment by charmoniumQ** [comment]
Update the existing one in `docs/default_plugins.md`.

Revise the structure of the documentation (and graph) for clarity.

**Comment by mhuzai** [comment]
This should also be added to README of each plugin. It exists for some plugins, e.g. timewarp, but is outdated.
