### ISSUE TITLE
Separate out Qemu setup from main setup

### ISSUE THREAD

**Issue by mhuzai** [ILLIXR/ILLIXR#188]
It doesn't make sense to have the `qemu` setup as part of `install_deps.sh`. If someone wants virtualization because they can't build ILLIXR natively, `install_deps.sh` might fail before they get to the `qemu` step. They can say "no" to all the other installs but _have_ to say "yes" to `install_apt_deps` and that has a lot of other dependencies that may or may not install correctly. So there should just be a separate `qemu` setup script to keep things clean.

Another advantage of a separate `qemu` setup script would be that users who _don't_ want `qemu` won't have unnecessary dependencies installed on their machine anymore.

**Comment by astro-friedel** [comment]
The new cmake build system should address this.
