### ISSUE TITLE
Local CI/CD testing: Instructions and install scripts need updating

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#190]
The [Debugging ILLIXR](https://github.com/ILLIXR/ILLIXR/blob/master/docs/debugging_illixr.md) page should also show how to build, run, and test the docker CI/CD flow without needing to create a PR and push changes.

Concerns to address in the updated instructions:
- `install_apt_deps.sh` needs to add docker as a dependency if the user wishes to test locally. Should this be a prompt, or default behavior?
- How many resources does the CI/CD flow need? How long does it take?
- The docker file needs some updates (use of `apt` vs `apt-get`).

**Comment by e3m3** [comment]
Is there anything else we would like to consider for local testing?

**Comment by mhuzai** [comment]
- Docker install should be a prompt.
- Don't worry about CI/CD resources. They are not in our hands and GitHub can do whatever with them. So we shouldn't make any assumptions.

Rest looks good!

**Comment by e3m3** [comment]
>     * Don't worry about CI/CD resources. They are not in our hands and GitHub can do whatever with them. So we shouldn't make any assumptions.

For sure, I was thinking of just noting in the document an order of magnitude for these as a warning for those running on thinking of testing on light hardware.

**Comment by mhuzai** [comment]
Makes sense!
