### ISSUE TITLE
New user experience: Clean and update documentation

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#191]
The documentation available at the [project docs site](https://illixr.github.io/ILLIXR/) contains a number of outdated information, broken links, typos, and unclear descriptions (for users with no background on the project).

This WIP issue will serve to coalesce changes to the documentation needed for the new user experience.

**Comment by e3m3** [comment]
- [Home](https://illixr.github.io/ILLIXR/)
- [Building illixr](https://illixr.github.io/ILLIXR/building_illixr/)
  - [ ] Typo: "ILLIR"
  - [ ] Context: "Switchboard" and other project specific terms are mentioned very early here without reference/definition
  - [ ] Context: A generalized schema code block for the yaml plugins could be illustrative
  - [ ] Update: How do we clean up
- [Debugging illixr](https://illixr.github.io/ILLIXR/debugging_illixr/)
  - (See Issue #190)
- [Getting started](https://illixr.github.io/ILLIXR/getting_started/)
  - [ ] Update: Explain why/when the `master` branch should be used instead of `v2-latest`
  - [ ] Context: Explain when `https` vs `ssh` should be used (for unaffiliated contributors)
  - [ ] Update: git submodules are gone right? (Also "update" is bolded)
  - [ ] Bug: "Default Components" link 404s
  - [ ] Context: Component definitions for "Spindle," "Switchboard," and Phonebook appear here. This Section should come earlier in the docs, and visually indicate the terms defined. Links to these definitions elsewhere in the document could be helpful too. This might also not be the right place for these to appear.
- [Illixr plugins](https://illixr.github.io/ILLIXR/illixr_plugins/)
  - [ ] Context: `ground_truth_slam`: The same dataset as what? What is a ground truth?
  - [ ] Typo: `gtsam_integrator`: "... fast-pose everytime a new IMU sample. ..."
  - [ ] Context: `pose_prediction`: A brief how, why, or what would be nice here
  - [ ] Todo: `audio` and `hologram` (also is this because of CUDA?)
  - [ ] Bug: "APU documentation" link 404s
  - [ ] Context: Use of "they" for descriptions in plugins+topics flow
  - [ ] Typo: "trough filing" (this bullet perhaps needs a clearer structure too)
- [Modifying a plugin](https://illixr.github.io/ILLIXR/modifying_a_plugin/)
  - [ ] Context: Brief info about the audio_pipeline plugin or link to readme
  - [ ] Context: Add sample filenames or where configs are located
  - [ ] Context/Style: Pushing to upstream ILLIXR first appears here
- [Monado illixr runtime overview](https://illixr.github.io/ILLIXR/monado_illixr_runtime_overview/)
  - [ ] Style: First appearance of numbered sections
  - [ ] Context: More dangling references to "phonebook" and "switchboard"
  - [ ] Typo: "... runtime so file ..."
  - [ ] Typo: "... drivers starts ..."
  - [ ] Style: "... into the current (the app's) ..." -> "... into the (app's) current ..."
  - [ ] Context: Each plugin should _not_ block *and* _not_ start a thread? Or start a thread should it need to block?
  - [ ] Style: A list description for some of these process could be easier to parse than a paragraph (e.g. Section 3, paragraph 2)
  - [ ] Style: "... intersection of ..." -> "... interface of ..."
  - [ ] Context: Antecedents for "it" in Section 4
  - [ ] Context: The translation plugin is yet another thread, right?
- [Monado integration dataflow](https://illixr.github.io/ILLIXR/monado_integration_dataflow/)
  - [ ] Typo: "... two client compositor ..."
  - [ ] Context: Could provide references for compositors, Vulkan, etc.
  - [ ] Context: Where does (or could) the last pose query call from? What does it mean not to use the application's pose at render?
  - [ ] Context: What does it mean for a pose not to vary according to a space?
  - [ ] Context: Explanation of "swapchain"
  - [ ] Style: The numbered list at the bottom could be larger sections with detailed and break out into discussion if needed
- [Visualizer logger](https://illixr.github.io/ILLIXR/visualizer_logger/)
  - [ ] Context: Seems odd to tell the user about the visualizer and then tell them not to use it :P
- [Writing your plugin](https://illixr.github.io/ILLIXR/writing_your_plugin/)
  - [ ] Context: Antecedent in "With this, ..."
  - [ ] Context: Common vs General -> Native ILLIXR plugins vs Non-native ILLIXR plugins?
  - [ ] Context: What are the shared prerequisites for common case vs general case?
  - [ ] Context: Add filename comments to larger code blocks
  - [ ] Context: Code blocks should be sample files in the repository
  - [ ] Style: Bullets 4+5 should be underneath in bullet 3
  - [ ] Context: Bullet 5's "or no concurrency" ambiguous with bullet 4
  - [ ] Context: Mention of "spindle"
- [Contributing](https://github.com/ILLIXR/ILLIXR/blob/master/CONTRIBUTING.md)
  - [ ] Bug: "API documentation" link 404s
  - [ ] Context: Add rebasing details to the branch discussion (are there instructions elsewhere for this?)
  - [ ] Context: It would be better to make a new config file for the new flow rather than update `configs/native.yaml`
  - [ ] Context: "First, we can ..." section and example arrive abruptly

**Comment by charmoniumQ** [comment]
It looks like the Doxygen docs failed to deploy?

`doxygen doxygen.conf` should generate those.
