### ISSUE TITLE
Add record_imu_cam

### ISSUE THREAD

**Issue by yingj4** [ILLIXR/ILLIXR#199]
This issue is to add the record_imu_cam pluggin and confirm that it could work with the given version. You don't need to modify anything.

**Comment by charmoniumQ** [comment]
This would be covered by #51 .

**Comment by mhuzai** [comment]
This has already been implemented in branch `issue-199-add-record_imu_cam-paper-2.2`. We just need to test it out a bit more and open a PR.

**Comment by mhuzai** [comment]
@hungdche, you worked on this, right? Why was the code not merged in?
