### ISSUE TITLE
Switch languages for the runner's config's schema

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#205]
|                                 | [attr] | [jsonschema] | [yamale] | [namedtuple] | [dataclasses] |
|---------------------------------|--------|--------------|----------|--------------|---------------|
| **Easy to read**                | Y      |              | Y        | Y            | Y             |
| **Statically type-checkable**   | Y      |              |          | Y            | Y             |
| **Python-native**               | Y      |              |          | Y            | Y             |
| **Arbitrary validators**        | Y      |              |          |              | Y             |
| **Convertible from YAML**       | Y      | Y            | Y        |              |               |
| **Convertors (like `pathify`)** | Y      |              |          |              | Y             |
| **Language-neutral**            |        | Y            |          |              |               |

# Pros of [attr]

- **Easy to read:** [jsonschema] is difficult to read and maintain.
- **Statically type-checkable:** [attr] is compatible with [mypy], so one statically type-check the code which uses the config object (unlike jsonschema and [yamale]). [Here][config_error] is a real example where I forgot the structure of the config that [attr]+[mypy] could have caught; In the current system, I didn't notice until CI failure.
- **Python-native:** [attr] with [mypy] can make it easier to call the runner from Python (unlike [yamale] which requires the data to start as YAML). This makes it easier to script experiments that invoke ILLIXR's runner with multiple configurations.
- **Arbitrary validators:** [attr] can have arbitrarily-complex validation on the fields passed into it (unlike [jsonschema], [yamale], and [namedtuple]). This could be how we make sure that every switchboard topic subscribers have a publisher. This could be how we test if the plugins support the same version of `common` (each plugin would need a metadata file, which could be looked up in the validator).
- **Convertible from YAML:** It is easy to parse YAML/json with [attr] because each field can have a "convertor" that turns constructs the field sub-object for each field. With [dataclasses] and [namedtuple], one would have to recursively convert every field.

    ```
    @attr.s
    class Config:
        # Unfortunately, `Loader` has to be repeated twice: once for mypy and once for attr.
        loader: Loader = attr.ib(convertor=Loader)

    @attr.s
    class Loader:
        name: str

    def main() -> None:
        ...
        config = Config(yaml.load(f))
        print(config.loader.name)
        # config.loader is already converted from a dict to a `Loader` object.
        # Same for all of its fields, recursively.
    ```
- **Convertors (like `pathify`)** Calls to `pathify` can be written into `attr` as convertors rather than called explicitly (unlike [jsonschema], [yamale], [dataclasses]. and [namedtuple], which do not have convertors). This is possible with `dataclasses` mechanism `__post_init__`, since the convertor is of the same type.

# Cons of [attr]

- **Language-neutral:** Unlike [jsonschema], [attr] is Python-specific. We could generate a jsonschema spec from the attr spec, but this is an extra step.

[config_error]: https://github.com/ILLIXR/ILLIXR/pull/203/commits/04974dabb68b34623faa6c2c3193d5e336278599
[jsonschema]: https://json-schema.org/
[attr]: https://www.attrs.org/en/stable/index.html
[yamale]: https://pypi.org/project/yamale/
[mypy]: https://mypy.readthedocs.io/en/stable/
[dataclasses]: https://docs.python.org/3/library/dataclasses.html
[namedtuple]: https://docs.python.org/3/library/collections.html#collections.namedtuple

**Comment by astro-friedel** [comment]
The upcoming CMake build system removes the runner, so this issue is moot.
