### ISSUE TITLE
GTSAM and other modules should build without `-march=native`

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#206]
When running ILLIXR on `aarch64` (Jetson AGX Xavier), compilation of GTSAM and Kimera-VIO fail due to the unsupported `-march=native` flag.

This issue fix should:
- [ ] Adapt flags for the GTSAM compilation on `x86_64` and `aarch64`
- [ ] Adapt flags for the Kimera-VIO compilation on `x86_64` and `aarch64`
- [ ] Integrate the changes in ILLIXR for the dependent modules

**Comment by saitiku** [comment]
For GTSAM, if building on Jetson platform - you can get around the problem by adding ```GTSAM_BUILD_WITH_MARCH_NATIVE=OFF``` to the cmake flags in ```scripts/install_gtsam.sh``` file.

**Comment by yichez16** [comment]
I met the same issue to deploy it on Jetson AGX Xavier. 
For GTSAM, I fixed the issue by adding above commands.
But for kimera_vio, it does not support "-march=native" flag.
Could you help me fix the issue?
Please the error listed below.

clang: error: the clang compiler does not support '-march=native'
  clang: error: the clang compiler does not support '-march=native'
  clang: error: the clang compiler does not support '-march=native'
  make[3]: *** [CMakeFiles/kimera_vio.dir/src/dataprovider/DataProviderInterface-definitions.cpp.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[3]: *** [CMakeFiles/kimera_vio.dir/src/dataprovider/DataProviderModule.cpp.o] Error 1
  make[3]: *** [CMakeFiles/kimera_vio.dir/src/dataprovider/DataProviderInterface.cpp.o] Error 1
  clang: error: the clang compiler does not support '-march=native'
  make[3]: *** [CMakeFiles/kimera_vio.dir/src/dataprovider/EurocDataProvider.cpp.o] Error 1
  make[2]: *** [CMakeFiles/kimera_vio.dir/all] Error 2
  make[1]: *** [all] Error 2

**Comment by astro-friedel** [comment]
GTSAM's default build is with -march=native turned off, and we no longer support Kimera.
