### ISSUE TITLE
Unfuse IMU and cam topics

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#210]
Affects: `offline_imu_cam`, `zed`,`realsense`, `OpenVINS`, `Kimera-VIO`, `gtsam_integrator`, and `rk4_integrator`.

**Comment by mhuzai** [comment]
#197 (which also addresses #196) will take care of this. Or are they missing something?

**Comment by charmoniumQ** [comment]
Yeah; I was not aware of #197 .
