### ISSUE TITLE
Preserve partial progress in our `Makefile`

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#213]
We compile-and-link in one step like so:

```
${CXX} blah.cpp blah2.cpp ...
```

This means that if _any_ of the `.cpp` files change, we recompile all of them. Instead, we should compile and link in two steps.

```
# For each CPP file
${CXX} blah.cpp -o blah.dbg.o

${CXX} blah.dbg.o blah2.dbg.o ... -o plugin.dbg.so
```

This might require converting some things in `common/` from `.hpp` to `.cpp`.

Also see why OpenVINS recompilation takes so long.

**Comment by charmoniumQ** [comment]
See #42.

**Comment by astro-friedel** [comment]
The new CMake build system is much smarter about only building file which have changed and linking is a separate step as well.
