### ISSUE TITLE
Evaluate Nix as the system package manager

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#246]
To ensure that we have reproducible development and testing environments, we need a portable way to manage package dependencies. A portable package management system that's common across CI deployments and user machines will help avoid inconsistent build environments which cause mysterious failures (see #242).

We may be able to address these issues using Nix ([Project page](https://nixos.org/)).

**Comment by charmoniumQ** [comment]
See #104, but don't let that discourage this attempt.

**Comment by astro-friedel** [comment]
The upcoming CMake build system deployment makes this moot.
