### ISSUE TITLE
Monado integration build error

### ISSUE THREAD

**Issue by ltstein** [ILLIXR/ILLIXR#257]
So, following https://illixr.github.io/ILLIXR/getting_started for V2 which looks like V-latest is 2.1.10

`git clone --recursive --branch v2-latest https://github.com/ILLIXR/ILLIXR`

`git submodule update --init --recursive`

`./install_deps.sh -j 8` and answering yes for all except QEMU

``./runner.sh configs/native.yaml` seems to run ok, I get the debug, extended window for HMD, and terminal printout

Issue is trying to use the monado integration 

`./runner.sh configs/monado.yaml`
 
I end up with 

> stderr:
>   /home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp: In function ‘int illixr_rt_launch(illixr_hmd*, const char*, const char*, void*)’:
>   /home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp:175:76: error: call of overloaded ‘create(const char*&)’ is ambiguous
>     175 |  dh->runtime_lib = new ILLIXR::dynamic_lib{ILLIXR::dynamic_lib::create(path)};
>         |                                                                            ^
>   In file included from /home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp:31:
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:39:21: note: candidate: ‘static ILLIXR::dynamic_lib ILLIXR::dynamic_lib::create(const string&)’
>      39 |  static dynamic_lib create(const std::string& path) {
>         |                     ^~~~~~
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:43:21: note: candidate: ‘static ILLIXR::dynamic_lib ILLIXR::dynamic_lib::create(const string_view&)’
>      43 |  static dynamic_lib create(const std::string_view& path) {
>         |                     ^~~~~~
>   /home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp:175:77: error: no matching function for call to ‘ILLIXR::dynamic_lib::dynamic_lib(<brace-enclosed initializer list>)’
>     175 |  dh->runtime_lib = new ILLIXR::dynamic_lib{ILLIXR::dynamic_lib::create(path)};
>         |                                                                             ^
>   In file included from /home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp:31:
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:28:2: note: candidate: ‘ILLIXR::dynamic_lib::dynamic_lib(ILLIXR::dynamic_lib&&)’
>      28 |  dynamic_lib(dynamic_lib&& other)
>         |  ^~~~~~~~~~~
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:28:2: note:   conversion of argument 1 would be ill-formed:
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:23:2: note: candidate: ‘ILLIXR::dynamic_lib::dynamic_lib(ILLIXR::void_ptr&&)’
>      23 |  dynamic_lib(void_ptr&& handle)
>         |  ^~~~~~~~~~~
>   /home/lincoln/dev/ILLIXR/runtime/common/dynamic_lib.hpp:23:2: note:   conversion of argument 1 would be ill-formed:
>   make[2]: *** [src/xrt/drivers/CMakeFiles/drv_illixr.dir/build.make:76: src/xrt/drivers/CMakeFiles/drv_illixr.dir/illixr/illixr_device.cpp.o] Error 1
>   make[1]: *** [CMakeFiles/Makefile2:597: src/xrt/drivers/CMakeFiles/drv_illixr.dir/all] Error 2
>   make: *** [Makefile:136: all] Error 2

**Comment by mhuzai** [comment]
This is a bug in the monado integration. We updated the dynamic lib interface in ILLIXR but forgot to change it inside the monado integration. We can push a fix, but in the meantime, can you try changing
```
/home/lincoln/dev/ILLIXR/.cache/paths/https%c%s%sgithub.com%sILLIXR%smonado_integration.git/src/xrt/drivers/illixr/illixr_device.cpp:175
```

from
```
dh->runtime_lib = new ILLIXR::dynamic_lib{ILLIXR::dynamic_lib::create(path)};
```

to
```
dh->runtime_lib = new ILLIXR::dynamic_lib{ILLIXR::dynamic_lib::create(std::string{path})};
```

**Comment by ltstein** [comment]
I was able to work around this issue for now by casting the argument 
`dh->runtime_lib = new ILLIXR::dynamic_lib{ILLIXR::dynamic_lib::create((std::string) path)};`

I then ran into the issue where `KIMERA_ROOT` was undefined. Comparing the yaml and functions in main.py, 
I added `KIMERA_ROOT=config["action"]["kimera_path"],`  to the `env_override` dict for subprocess run in the `monado_load` function for the runner `main.py.` I also added `kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/` the the `monado.yaml.` Now, running I see the OpenXR simple example with the tracking of the `mav0` test data.

**Comment by mhuzai** [comment]
Looks like our posts crossed.

Thanks for the update. We've been moving towards tighter integration with Monado and have ILLIXR as part of the main Monado repo now. However, our configs within the ILLIXR repo have lagged behind a little bit, so thanks for testing them out and giving feedback.

If you want, you can open a PR with the above fixes and contribute to ILLIXR, or we can just fix it on our end.
