### ISSUE TITLE
Expand `realsense` camera support to T26x

### ISSUE THREAD

**Issue by ltstein** [ILLIXR/ILLIXR#259]
As I understand it, ILLIXR currently supports the D435i camera. I would like to target a broader range of the Realsense hardware, starting with the T26x variants although they do not support as high a rate of IMU data. Primary motivation is most Project North Star headsets have this as the default tracking solution so this would enable those users to leverage the ILLIXR framework for future development.   First look, it appears it would mostly be allowing alternate values for the `constexpr`s in `plugin.cpp` but I don't know if a configurable plugin or completely separate plugin would be preferred considering the whole framework.

**Comment by mhuzai** [comment]
Thanks for looking into this!

Configurable plugin would be the way to go because most of the code is the same, and it should hopefully just be a matter of detecting which camera is attached and then setting the parameters correctly. @Hyjale actually did run a T265 at some point, so he can shed some light on this.

**Comment by Hyjale** [comment]
Hi, 

I actually didn't get the chance to run with the T265. I would recommend creating a separate plugin for the T26x sensors since those have pose data built-in. 

For reference: https://github.com/IntelRealSense/librealsense/blob/master/examples/pose/rs-pose.cpp

**Comment by mhuzai** [comment]
This can be easily and cleanly done within one plugin. We can query the attached camera by using [query_devices()](https://intelrealsense.github.io/librealsense/doxygen/classrs2_1_1context.html#a0e0bfd3451cab5a32ab78f8037a4d793), and then configure it appropriately. [This page](https://github.com/IntelRealSense/librealsense/tree/master/examples/sensor-control) provides good examples of querying device information.

Also, ILLIXR's camera/IMU plugins do **not** publish poses. They only publish RGB/grayscale images and IMU values, and optionally depth images. So we shouldn't be worrying about pose in this plugin.

**Comment by ltstein** [comment]
> This can be easily and cleanly done within one plugin. We can query the attached camera by using [query_devices()](https://intelrealsense.github.io/librealsense/doxygen/classrs2_1_1context.html#a0e0bfd3451cab5a32ab78f8037a4d793), and then configure it appropriately. [This page](https://github.com/IntelRealSense/librealsense/tree/master/examples/sensor-control) provides good examples of querying device information.
> 
> Also, ILLIXR's camera/IMU plugins do **not** publish poses. They only publish RGB/grayscale images and IMU values, and optionally depth images. So we shouldn't be worrying about pose in this plugin.

Thanks for the reference links. I definitely intended this addition to follow the current architecture of providing raw data image and IMU data that would be processed by the other plugins. Will put in a draft PR for further discussion once I have a prototype.
