### ISSUE TITLE
CI should build and run all plugins

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#270]
Currently, we only receive feedback for runs on CI using `configs/ci.yaml`. Some existing flows cannot run under CI yet (e.g. `configs/native.yaml`). Some existing flows cannot build under CI yet (e.g. OpenCV with CUDA enabled). For flows that build but cannot run in CI, we should make a build-only config that includes the modules and compiles the project.

The following plugins are currently built and run:
- `configs/ci.yaml`:
    - `timewarp_gl`
    - `audio`
    - `offline_imu_cam`
    - `pose_prediction`
    - `ground_truth_slam`
    - `gldemo`
    - `Kimera-VIO`
    - `gtsam_integrator`

Minimally, we need the following flows to run in CI:
- `configs/ci/`:
    - `run-solo.yaml`:
        - `offline_imu_cam.yaml`
        - `pose_prediction.yaml`
        - `ground_truth_slam.yaml`
        - `kimera-vio.yaml`
        - `openvins.yaml`
        - `rk4_integrator.yaml`
        - `gtsam_integrator.yaml`
        - `offload_data.yaml`
    - `build-only.yaml`:
        - `audio.yaml` # May move to `run-solo` with hotfix
        - `debugview.yaml`
        - `gldemo.yaml`
        - `timewarp_gl.yaml`
    - `no-build.yaml`:
        - `hotlab.yaml`
        - `zed.yaml` # May move to `build-only`
        - `realsense.yaml` # May move to `build-only`
        - `opencv-with-cuda.yaml` # Not a plugin
        - `monado_integration.yaml` # May move to `build-only`
        - `monado_openxr_app.yaml` # May move to `build-only`
        - `pose_lookup.yaml` # Will move to `run-solo` with hotfix (#32)
    - `flows/`:
        - `kimera-gtsam.yaml`:
            - `timewarp_gl`
            - `audio`
            - `offline_imu_cam`
            - `pose_prediction`
            - `ground_truth_slam`
            - `gldemo`
            - `Kimera-VIO`
            - `gtsam_integrator`
            - `offload_data`
        - `kimera-rk4.yaml`:
            - `timewarp_gl`
            - `audio`
            - `offline_imu_cam`
            - `pose_prediction`
            - `ground_truth_slam`
            - `gldemo`
            - `Kimera-VIO`
            - `rk4_integrator`
            - `offload_data`
        - `openvins-gtsam.yaml`:
            - `timewarp_gl`
            - `audio`
            - `offline_imu_cam`
            - `pose_prediction`
            - `ground_truth_slam`
            - `gldemo`
            - `OpenVINS`
            - `gtsam_integrator`
            - `offload_data`
        - `openvins-rk4.yaml`:
            - `timewarp_gl`
            - `audio`
            - `offline_imu_cam`
            - `pose_prediction`
            - `ground_truth_slam`
            - `gldemo`
            - `OpenVINS`
            - `rk4_integrator`
            - `offload_data`
        - `lookup.yaml`:
            - `timewarp_gl`
            - `audio`
            - `offline_imu_cam`
            - `pose_prediction`
            - `gldemo`
            - `pose_lookup`
            - `rk4_integrator`
            - `offload_data`

**Comment by mhuzai** [comment]
This is great. We also need a `native-lookup.yaml` flow -- we actually ran into a compilation error last night! @JeffreyZh4ng, can you upstream the fixes when you get a chance, please?

**Comment by e3m3** [comment]
> This is great. We also need a native-lookup.yaml flow -- we actually ran into a compilation error last night! @JeffreyZh4ng, can you upstream the fixes when you get a chance, please?

Note that some of this may have been addressed by [this commit on #32](https://github.com/ILLIXR/ILLIXR/pull/32/commits/2d8644474e6d8cc656ee0b8e0880e9617cdc94cc)

**Comment by mhuzai** [comment]
Ha, yes, fixed!

**Comment by e3m3** [comment]
> Currently, we only receive feedback for ...

- Added `offload_data` to new configs.
- Added config 'configs/ci-lookup.yaml`.

**Comment by e3m3** [comment]
TBD: `debugview`.

**Comment by charmoniumQ** [comment]
Let's make a `configs/ci` a directory?

**Comment by e3m3** [comment]
Added `solo/`, `build-only/`, `no-build/`, and `flows/` to `configs/ci/`.

**Comment by e3m3** [comment]
Added `pose_lookup` and `empty.yaml`

**Comment by e3m3** [comment]
Added `monado-integration.yaml` and `monad-openxr-app.yaml`.

**Comment by e3m3** [comment]
> Minimally, we need the following flows to run in CI: ...

- Updated: `configs/ci/solo/` -> `configs/ci/run-solo.yaml`
- Updated: `configs/ci/build-only/` -> `configs/ci/build-only.yaml`
- Updated: `configs/ci/no-build/` -> `configs/ci/no-build.yaml`
- Removed: `configs/ci/run-solo.yaml: empty.yaml`
- Moved: `pose_lookup.yaml`
- Moved: `timewarp_gl.yaml`
- Moved: `audio.yaml`
- Moved: `gldemo.yaml`

**Comment by astro-friedel** [comment]
This PR is superceded by the upcoming testing framework
