### ISSUE TITLE
Please check if xvfb-run command in headless.yaml is correct.

### ISSUE THREAD

**Issue by K-Wu** [ILLIXR/ILLIXR#277]
It seems to me that line 26 in configs/headless.yaml should be 

```
  command: xvfb-run $cmd
```

instead of
```
  command: xvfb-run %a
```

The former can be executed successfully on my machine but the later won't.

Link to the code: https://github.com/ILLIXR/ILLIXR/blob/5277855b4148a468377c96d534aac5f8383220eb/configs/headless.yaml#L22

**Comment by charmoniumQ** [comment]
You are correct.

We used to use `%a`, but I switched it over to `$cmd` since that is more descriptive; Evidently, I missed a reference.

Please submit a PR or one of us will get around to it eventually.

**Comment by K-Wu** [comment]
Got it. Thanks for clarification! I created the PR #278 to fix this

**Comment by K-Wu** [comment]
I guess this issue can be closed as the related PR #278 is pending approval.

**Comment by mhuzai** [comment]
Reopening. It'll automatically get closed when the PR gets merged. This helps us with keeping track of things on our Kanban board.
