### ISSUE TITLE
Support for OAK-D type hardware

### ISSUE THREAD

**Issue by ltstein** [ILLIXR/ILLIXR#280]
Recently, Luxonis has developed and shipped the OAK-D, a stereo camera + RGB + IMU as well as on-device vision processing (Myriad X) https://docs.luxonis.com/en/latest/pages/products/bw1098obc/. This same hardware also is available in customizable configurations, making it an interesting platform for future research. 

It would be beneficial to add initial support for this hardware family, following the same interface as the current Realsense and Zed cameras.

**Comment by mhuzai** [comment]
Yup, this would be great!
