### ISSUE TITLE
Q&A: ILLIXR works on Windows, Linux, and MacOS, right?

### ISSUE THREAD

**Issue by bipul-mohanto** [ILLIXR/ILLIXR#328]

**Comment by mhuzai** [comment]
ILLIXR currently only works on Linux. We have an Android port in the works. We would like Windows support too, of course, but aren't working on it at the moment. If you'd like to contribute, that'd be great!

**Comment by bipul-mohanto** [comment]
Thanks for your reply, you are doing a wonderful job. I am looking for some API for real-time rendering for VR interaction, on windows.
