### ISSUE TITLE
Set up CI testing

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#35]
For most components, the best we can do is ensure it builds.
However, some components can also have tests `make test`.
In the past, broken code (non-compiling) has been pushed to master, so automating this has real benefit.

**Comment by charmoniumQ** [comment]
We only have 2000 hours for the free plan. There are some improvements we can make to mitigate that limitation.

- Use a base docker image with all the dependencies that don't change pre-built.
- Use ccache for everything, especially OpenVINS and libspatialaudio.
  - This will also help our local dev-test cycle.

**Comment by mhuzai** [comment]
We already have build tests now. What else needs to be done to satisfy this issue?

**Comment by charmoniumQ** [comment]
This issue is outdated. See #82
