### ISSUE TITLE
Add Code Reviewing Guidelines.

### ISSUE THREAD

**Issue by Madhuparna04** [ILLIXR/ILLIXR#357]

**Comment by Boyuan-Tian** [comment]
Let’s pass it through everyone before adopting.
I am putting the link below. Please take a look and leave comments when you have a chance.

Guidelines for PR reviewer:
https://google.github.io/eng-practices/review/reviewer/

Guidelines for PR submitter:
https://google.github.io/eng-practices/review/developer/

**Comment by astro-friedel** [comment]
Closing as this issue has been combined with similar ones in #415
