### ISSUE TITLE
Order of multiplication in modelview matrix calculation

### ISSUE THREAD

**Issue by yavuz650** [ILLIXR/ILLIXR#362]
In gldemo, I think the order of multiplication should be the other way around,

https://github.com/ILLIXR/ILLIXR/blob/38ef2007db0b3626900fd2a06371dc184c1315de/gldemo/plugin.cpp#L155

```diff
+ Eigen::Matrix4f modelViewMatrix = view_matrix * modelMatrix; 
- Eigen::Matrix4f modelViewMatrix = modelMatrix * view_matrix; 
```
I guess this didn't cause any problems because the model matrix is identity anyways.

**Comment by Jebbly** [comment]
Thanks for reporting this! You are correct and a PR has been created to address this issue.
