### ISSUE TITLE
Running Sponza/Materials benchmarks

### ISSUE THREAD

**Issue by pcg108** [ILLIXR/ILLIXR#380]
Hi, 

Is it possible to run the Sponza, Materials, Platformer, and AR demo benchmarks mentioned in the ILLIXR [paper](http://rsim.cs.illinois.edu/Pubs/IISWC_2021_ILLIXR.pdf) with this repo? I don't see any links in the config files to download and run those. Any help would be greatly appreciated!

**Comment by charmoniumQ** [comment]
Those benchmarks are OpenXR applications which can be run with Monado. Follow the documentation [here](https://illixr.github.io/ILLIXR/building_illixr/) to Monado with ILLIXR.
