### ISSUE TITLE
eulerAngles is deprecated 

### ISSUE THREAD

**Issue by jianxiapyh** [ILLIXR/ILLIXR#406]
in gtsam, we need to update since it is marked deprecated in newer Eigen versions
```        Eigen::Matrix<double, 3, 1> rotation_angles =
            original_quaternion.toRotationMatrix().eulerAngles(0, 1, 2).cast<double>();
```

**Comment by astro-friedel** [comment]
In looking at the documentation for the most recent release (3.4.0) and on the dev branch, I see no reference to this function being deprecated now, or in the near future.
