### ISSUE TITLE
Is ZED mini camera support deprecated?

### ISSUE THREAD

**Issue by izenderi** [ILLIXR/ILLIXR#414]
I am trying to connect the ZED mini camera to the ILLIXR but I have received the following error when running main.dbg.exe:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  dlopen("libplugin.zed.dbg.so"): libplugin.zed.dbg.so: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
```
However, when I checked the libplugin.zed.dbg.so appears in `/usr/local/lib/libplugin.zed.dbg.so` alongside with other plugins. 

Host Machine (Both are tested)
1. PC: Ubuntu20.04 with CUDA12.3 RTX3060
2. AGX Xiavier 16GB: 20.04 with CUDA12.1 

Here is my step-by-step actions (Following this page: https://illixr.github.io/ILLIXR/using_cameras/):
1. Install the ZED mini SDK and verified with the ZED hello tutorial: https://www.stereolabs.com/docs/tutorials/hello-zed
2. in the openvins uncomment the line `#define ZED`. made a commit and replace the ILLIXR GetOpenVINS.cmake GIT_TAG. (https://github.com/izenderi/open_vins_illixr/commit/1843b92c3a6cbc811c1b2eeb9b62f8ad3baec6db)
3. Download the setting file from calib.stereolabs.com and put it in /usr/local/zed/settings/
4. Normal compile the ILLIXR with the following profile yaml:
```
plugins: zed,gtsam_integrator,pose_prediction,gldemo,timewarp_gl,debugview,offload_data,audio_pipeline
visualizers: openvins
enable_offload: false
enable_alignment: false
enable_verbose_errors: false
enable_pre_sleep: false
```

So I was wondering if the zed camera support has been taken out? When I take out the zed plugin everything can be then executed successfully. If it is taken down, is there any workaround?

**Comment by astro-friedel** [comment]
The Zed camera is still supported. In order to try and diagnose your issue, could you run the following commands and send the outputs:

1. ldd /usr/local/lib/libplugin.zed.dbg.so

2. ldd /usr/local/zed/lib/libsl_zed.so   (I am assuming this is the path to this library)

3. What version of the Zed SDK did you install?

4. With the Zed camera plugged in run /usr/local/zed/tools/ZED_Explorer. Does it detect your camera? (I am assuming the path for this)

**Comment by izenderi** [comment]
Thanks for the help! I have tested again from the clean master branch and it works on PC. Will check with the Xaiver later and see anything pop up!

**Comment by izenderi** [comment]
I have found out the cause of the issue:

When `cmake --install .` using sudo, it did not properly link the libplugin.zed.dbg.so since it is . To avoid further confusion or ambiguity, launch the executable from build directory directly will solve the issue. Thus closing the issue
