### ISSUE TITLE
Separate IMU/camera Switchboard topics

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#50]
Or explain why we shouldn't.
This currently complicates the ZED code (where the Camera thread has to send frames to the IMU thread, which pairs them and sends them on a Switchboard topic).
This currently simplifies OpenVINS (where we need to process the camera after the IMU).

**Comment by mhuzai** [comment]
Now that we are integrating scene reconstruction, this issue will come up again. A camera can have multiple consumers, but not all of them may require IMU data. Given our past discussion about visibility, should we have this discussion on gitter?

**Comment by astro-friedel** [comment]
I believe PR #372 addressed this issue.

**Comment by astro-friedel** [comment]
This should now be addressed.
