### ISSUE TITLE
Fix `install_deps.sh`

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#70]
- Install Python3.8 (safely, with [pyenv](https://github.com/pyenv/pyenv))
- Install Poetry with Python3.8
- Install clang-10
- Make clang-10 default (don't want to `export` every time).
- Install curl, zip.

**Comment by mhuzai** [comment]
Most of these changes are no longer required, and the rest have been taken care of. Should we link to the appropriate PR and close?
