### ISSUE TITLE
Replace `std::mutex` with `std::shared_mutex`

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#75]
A `std::shared_mutex` permits EITHER n readers OR 1 writer.

- When a thread reads a datastructure, it only needs to acquire `std::shared_lock`. This permits parallel reads, since they don't conflict, but locks out all writers.
- When a thread writes a datastructure, it needs to acquire `std::unique_lock`. This locks out all other writers and all readers.

**Comment by immanuelsavio** [comment]
Can you assign this issue to my name

**Comment by mhuzai** [comment]
@charmoniumQ, is this still an open issue? Are there any known places where the mutexes can be replaced?

**Comment by charmoniumQ** [comment]
- `common/sqlite_record_logger.hpp` needs this (additionally the read is unsynchronized, so needs a `shared_lock` there, and the existing lock can be a `unique_lock`).
- `common/phonebook.hpp` needs this.
- However, `runtime/switchboard_impl.hpp` does _not_ need this, if we merge in #32 .

**Comment by immanuelsavio** [comment]
I have made the required changes here #158
