### ISSUE TITLE
Improve install_deps.sh

### ISSUE THREAD

**Issue by mhuzai** [ILLIXR/ILLIXR#91]
Print detailed message listing exactly what will be installed.

**Comment by e3m3** [comment]
For the package dependencies, we can print all packages to be sent to 'apt-get'. 'apt-get' subsequently which packages will actually be installed. Another option is to find out which packages will be installed by 'apt-get' using the provided package list, and print that instead.

For the other install scripts, 'cmake' is generally used to build the packages, followed by a 'make install'. What is the correct behavior for these dependencies? We already prompt the user asking whether each dependent library should be installed.

**Comment by mhuzai** [comment]
The original intent of this was that we should tell the user what the intent of the script is _before_ we start prompting them for individual dependencies. This would be more detailed information than just "install DBoW2?" It would say what we need DBoW2 for, for instance.
But this may be unnecessary now. The queries give enough high-level information, and if we print the apt packages, that might be sufficient. Open to ideas.

What did you think was lacking in install_deps when you ran it?

**Comment by e3m3** [comment]
Based on what you said, I could see us printing list containing the relevant name for each prompt, and then subsequently do the prompts.

Regarding the apt packages, the package list is currently printed after the user prompt, but before installation (without an additional prompt). Given the current structure of the install scripts, this behavior is okay with me.

In general, I dislike prompts in scripts, but I could see the need for them for ILLIXR users. If the result of the large dependency list is that the project is tied to a handful of Ubuntu LTS distributions only, then I would say a more automated approach that detects missing/conflicting package or sets up a virtual environment would be best.

**Comment by mhuzai** [comment]
Yes, I agree that a more automated approach would be best but given our limited resources, what we have at the moment is alright.

As for the printing behavior, I think we're in agreement.

**Comment by charmoniumQ** [comment]
If we're already printing the packages that `apt-get` installs, I'd suggest also silencing the `stdout`. It's pretty redundant, anything significant goes to `stderr`, and I care about the signal-to-noise ratio of the script, so warnings do not get missed.
