### ISSUE TITLE
Configurable ILLIXR timeout

### ISSUE THREAD

**Issue by therishidesai** [ILLIXR/ILLIXR#94]
Currently, ILLIXR timesout with 60 seconds. We need a way to configure this time or turn the timeout off. This should probably be set in the config yaml file for runner.py.

**Comment by charmoniumQ** [comment]
See `ILLIXR_RUN_DURATION` in `runtime/main.cpp`.

**Comment by astro-friedel** [comment]
I believe this has been addressed for some time.
